DROP DATABASE IF EXISTS SHOP_DATABASE;
CREATE DATABASE SHOP_DATABASE;

USE SHOP_DATABASE;

DROP TABLE IF EXISTS  ITEMS;
CREATE TABLE  ITEMS (
    id int not null primary key AUTO_INCREMENT,
    name varchar(100) not null
);

INSERT INTO ITEMS(name) VALUES("Apple");
INSERT INTO ITEMS(name) VALUES("Knife");

SELECT * FROM SHOP_DATABASE.ITEMS;