DROP DATABASE IF EXISTS SHOP_DATABASE;
CREATE DATABASE SHOP_DATABASE;

USE SHOP_DATABASE;

DROP TABLE IF EXISTS  ITEMS;
CREATE TABLE  ITEMS (
    id int not null primary key AUTO_INCREMENT,
    name varchar(100) not null,
    category_id int not null
);
DROP TABLE IF EXISTS  CATEGORIES;
CREATE TABLE  CATEGORIES (
    id int not null primary key AUTO_INCREMENT,
    name varchar(100) not null
);

INSERT INTO ITEMS(name, category_id) VALUES("Apple", 1);
INSERT INTO ITEMS(name, category_id) VALUES("Pear", 1);
INSERT INTO CATEGORIES(name) VALUES("Food");

SELECT * FROM SHOP_DATABASE.ITEMS;
SELECT * FROM SHOP_DATABASE.CATEGORIES;